### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by aneilmac** [OlivierJG/botansqlite3#10]
What is the License attached to this library, is it open source?

**Comment by corytrese** [comment]
In the source files for BotaSqlite3:
"Distributed under the terms of the Botan license"

The Botan License is the  Simplified BSD https://botan.randombit.net/

Link to license: https://botan.randombit.net/license.txt

Hope that helps.

**Comment by aneilmac** [comment]
Many thanks! Helps a lot. :)

**Comment by corytrese** [comment]
No problem. A pretty common question, I think like 30% of the 10 tickets filed on this project were asking for the license :)

If you care to close this ticket, that might help save OlivierJG some time.
