### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Vdue** [OlivierJG/botansqlite3#3]
Olivier,
I have difficulties to get botansqlite working. I am on OSX 10.8.2 with XCode 4.5.2.

I downloaded the following:
Your botansqlite
Botan 1.10.3 from their website
SQLite3 amalgamation source from their website
Command Line Tools from Apple's website

Since I am not familiar with command line tools, I copied all and everything into one folder (Botan, botansqlite, SQLite3).

In the terminal window I did:
$ gcc -v
->gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

$ patch -p0 < sqlite3-amalgamation.patch
->success

$ gcc -c sqlite3.c -o botansqlite3.o && gcc -c codec.cpp -o codec.o `pkg-config --cflags botan-1.10.3` && ar rcs libbotansqlite3.a botansqlite3.o codec.o

That throws me errors:
-bash: pkg-config: command not found
In file included from codec.cpp:8:
codec.h:12:25: error: botan/botan.h: No such file or directory
....

Could you please point me into the right direction what I am doing wrong.

Thanks

Vdue

**Comment by OlivierJG** [comment]
The instructions are rather linux-centric at the moment, sorry about that. You dont have pkg-config, which isn't really a problem in this case. You can replace the call to pkg-config with botan-config-1.10 (or whatever version) or set the compiler flags manually.

Setting them manually should be as simple as passing the include path (ie, "-I/usr/include/botan-1.10").

**Comment by Vdue** [comment]
Thanks for the quick reply.

Well, I installed MacPorts to get pkg-config installed, that was missing.
Double checked botan:
release_major = 1
release_minor = 10
release_patch = 3

All my files are stored under: /Volumes/DATA/patch

In the terminal window:
export PKG_CONFIG_PATH=/Volumes/DATA/patch

gcc -c sqlite3.c -o botansqlite3.o && gcc -c codec.cpp -o codec.o `pkg-config --cflags botan-1.10.3` && ar rcs libbotansqlite3.a botansqlite3.o codec.o

->
Package botan-1.10.3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `botan-1.10.3.pc'
to the PKG_CONFIG_PATH environment variable

could you assist ?

**Comment by OlivierJG** [comment]
Unfortunately I'm not familiar enough with OSX to say how to configure pkg-config. Following the instructions in the error message should work, however.

Additionally, as I said before, you don't need pkg-config for botansqlite3, I listed some alternatives in my previous comment.
